from . import product_category_tag
from . import product_template
from . import packaging_details
from . import sale_order
from . import project_task
from . import sales_order_line
from . import hs_code
from . import shipping_terms
from . import bank_detail
from . import company
from . import partner
from . import res_users
from . import crm_lead_old_sale
from . import crm_tag
from . import res_currency
from . import ir_actions_report
